"""Workflows

Revision ID: 0342f48db31c
Revises: dfb5cde803da
Create Date: 2026-06-12 03:09:44.416669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0342f48db31c'
down_revision: Union[str, Sequence[str], None] = 'dfb5cde803da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.String(length=120), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_definitions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_definitions_trigger_event'), ['trigger_event'], unique=False)

    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('subject_ref', sa.String(length=120), nullable=False),
    sa.Column('subject_summary', sa.Text(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_instances_definition_id'), ['definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workflow_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_approvals_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approvals_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_approvals_instance_id'))

    op.drop_table('workflow_approvals')
    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_instances_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_definition_id'))

    op.drop_table('workflow_instances')
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_trigger_event'))
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_tenant_id'))

    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
