"""v1.0 Baseline: Tenancy, Auth, Geschäftsmodule, RAG

Revision ID: 4cffd8a4bcc1
Revises: 
Create Date: 2026-06-11 21:57:14.786195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cffd8a4bcc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_customers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('finance_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_net', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_expenses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hr_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('vacation_days_per_year', sa.Integer(), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hr_employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_employees_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_employees_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_employees_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_title'), ['title'], unique=False)

    op.create_table('rag_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_chunks_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('auth_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module')
    )
    with op.batch_alter_table('auth_role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email')
    )
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('crm_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_interactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_interactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('finance_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_net', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    with op.batch_alter_table('finance_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_invoices_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_invoices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hr_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hr_absences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_absences_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_absences_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_tasks_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_project_tasks_project_id'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('hr_absences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_absences_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_hr_absences_employee_id'))

    op.drop_table('hr_absences')
    with op.batch_alter_table('finance_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_finance_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_finance_invoices_customer_id'))

    op.drop_table('finance_invoices')
    with op.batch_alter_table('crm_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_interactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_interactions_customer_id'))

    op.drop_table('crm_interactions')
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_auth_users_email'))

    op.drop_table('auth_users')
    with op.batch_alter_table('auth_role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_role_permissions_role_id'))

    op.drop_table('auth_role_permissions')
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_chunks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_source_id'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_source'))

    op.drop_table('rag_chunks')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_title'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_category'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('hr_employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_employees_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_hr_employees_last_name'))
        batch_op.drop_index(batch_op.f('ix_hr_employees_department'))

    op.drop_table('hr_employees')
    with op.batch_alter_table('finance_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_expenses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_finance_expenses_category'))

    op.drop_table('finance_expenses')
    with op.batch_alter_table('crm_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_customers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_crm_customers_name'))

    op.drop_table('crm_customers')
    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_roles_tenant_id'))

    op.drop_table('auth_roles')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
