"""Builder: Custom-Module, Records, Drafts

Revision ID: 7628af7641a8
Revises: e5b1a3edeb07
Create Date: 2026-06-12 02:53:23.855221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7628af7641a8'
down_revision: Union[str, Sequence[str], None] = 'e5b1a3edeb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_plural', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug')
    )
    with op.batch_alter_table('custom_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_modules_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_modules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reference_target', sa.String(length=80), nullable=True),
    sa.Column('show_in_list', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['custom_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_fields_module_id'), ['module_id'], unique=False)

    op.create_table('custom_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['custom_modules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_records_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('builder_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description_input', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('erklaerung', sa.Text(), nullable=True),
    sa.Column('rueckfragen', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builder_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builder_drafts_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builder_drafts_tenant_id'))

    op.drop_table('builder_drafts')
    with op.batch_alter_table('custom_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_custom_records_module_id'))

    op.drop_table('custom_records')
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_fields_module_id'))

    op.drop_table('custom_fields')
    with op.batch_alter_table('custom_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_modules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_custom_modules_slug'))

    op.drop_table('custom_modules')
    # ### end Alembic commands ###
