"""Widgets

Revision ID: a8f679c78336
Revises: 0342f48db31c
Create Date: 2026-06-12 03:14:24.271728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f679c78336'
down_revision: Union[str, Sequence[str], None] = '0342f48db31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('widget_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('metric_field', sa.String(length=60), nullable=True),
    sa.Column('group_by', sa.String(length=60), nullable=True),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widgets_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widgets_tenant_id'))

    op.drop_table('widgets')
    # ### end Alembic commands ###
